### ISSUE TITLE
Deserialisation of objects not handled

### ISSUE THREAD

**Issue by richard-webb-dev** [Jaeger2305/werewolves-site#19]
Needs marrying with Angular.js

**Comment by richard-webb-dev** [comment]
game_manager seems to create 2 games.

Complicated by buggy event loop server side.

**Comment by richard-webb-dev** [comment]
Memory management of player/game needs fixing before I can look at this.

**Comment by richard-webb-dev** [comment]
#17 closely linked

**Comment by richard-webb-dev** [comment]
Nothing standing in the way now... and Angular 2 is out! More learning to be done!

Also, React.js, Flux, reflux, knockout, so many other options to pick, but Angular 2 seems top dog for a complete solution.

**Comment by Jaeger2305** [comment]
Also, React.js, Flux, reflux, knockout, so many other options to pick, but Angular 2 seems top dog for a complete solution.

**Comment by richard-webb-dev** [comment]
Neeeearly there. Need to sync games list in gameManager so that it's not just appending all the time.
Also, need to test when the gameManager.activeGame is updated (it seems to be straight after the timer on the delete for an empty game)

**Comment by richard-webb-dev** [comment]
Events are now deserialised. Imperfect information isn't achieved yet.

**Comment by richard-webb-dev** [comment]
activeGame updated on every game:g_id broadcast message (fine for now)

Finally closed! Woohoo! Many side tickets to come...
